MediaConvert support direct 'destination' output arg
samvera-labs/active_encode pull request #103
Opened 2022-04-20 15:59 UTC by jrochkind

Previously, you specified the output location  by configuring output_bucket globally, and then setting output_prefix on the create call.

These are combined by code to pass to MediaConvert as an s3://  url in the  destination parameter.

This PR provides an alternate option, just pass a `destination` arg with an s3:// url to create, not using output_bucket at all. This is an arg of the same format that MediaConvert itself uses, passed directly to MediaConvert. It is more convenient in some situations to simply pass the destinations on a per-call basis, the same way you would to MediaConvert.

2022-04-20 16:30 UTC, jrgriffiniii commented
https://app.circleci.com/pipelines/github/samvera-labs/active_encode does not indicate that the CircleCI jobs are actually being run. This is currently being discussed with the CircleCI administrators, so sorry for this.

2022-04-28 17:40 UTC, mbklein requested changes
👍🏻  but for one tiny two-letter transposition

2022-04-28 17:40 UTC, mbklein commented on guides/media_convert_adapter.md
> +You can also use `desitnation` instead of `output_prefix`, to supply a complete `s3://` url,
```suggestion
You can also use `destination` instead of `output_prefix`, to supply a complete `s3://` url,
```

2022-04-28 18:23 UTC, mbklein approved these changes

2022-04-28 18:23 UTC, merged